version: '3'

services:
  app:
    build: .
    command: npm start
    ports:
      - '2000:2000'
    volumes:
      - .:/usr/app

  db:
    container_name: 'database_node'
    image: mysql:5.7.31
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=r00t
      - MYSQL_DATABASE=db_node
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
      - TZ=America/Sao_Paulo
